[package]
name = "dns"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.2"
convert-base = "1.1.2"
itertools = "0.10.3"
radix_fmt = "1.0.0"
rustdns = "0.4.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[bin]]
name = "dns"
path = "main.rs"
